import chroma from 'chroma-js';

const styles = {
    ColorBox: {
        boxSizing: 'border-box',
        width: '20%',
        height: (props) => (props.showingFullPalette ? '25%' : '50%'),
        display: 'inline-block',
        margin: '0 auto',
        position: 'relative',
        cursor: 'pointer',
        verticalAlign: 'top',
        '&:hover .copyButton': {
            transform: 'scale(1)',
        },
    },
    autoTextColor: {
        color: (props) =>
            chroma(props.background).luminance() <= 0.4
                ? 'white'
                : 'rgba(0, 0, 0, 0.6)',
    },
    seeMore: {
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
        position: 'absolute',
        bottom: '0',
        right: '0',
        border: 'none',
        width: '60px',
        height: '30px',
        lineHeight: '30px',
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    copyButton: {
        transform: 'scale(0)',
        textDecoration: 'none',
        width: '100px',
        height: '30px',
        position: 'absolute',
        display: 'inline-block',
        top: '50%',
        left: '50%',
        marginLeft: '-50px',
        marginTop: '-15px',
        outline: 'none',
        textAlign: 'center',
        fontSize: '1rem',
        lineHeight: '30px',
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
        textTransform: 'uppercase',
        border: 'none',
        cursor: 'pointer',
    },
    boxContent: {
        position: 'absolute',
        width: '100%',
        padding: '10px',
        left: '0',
        bottom: '0',
        fontSize: '12px',
        textTransform: 'uppercase',
        letterSpacing: '1px',
    },
    copyOverlay: {
        opacity: '0',
        transform: 'scale(0)',
        zIndex: '0',
        width: '100%',
        height: '100%',
        transition: 'transform 600ms ease-in-out',
    },
    copyMsg: {
        position: 'fixed',
        top: '0',
        left: '0',
        bottom: '0',
        right: '0',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '4rem',
        transform: 'scale(0)',
        opacity: '0',
        color: 'white',
        transition: 'transform 300ms ease-in-out',
        transitionDelay: '200ms',
        '& h1': {
            textAlign: 'center',
            fontWeight: '400',
            textShadow: '1px 2px black',
            backgroundColor: 'rgba(255, 255, 255, 0.3)',
            width: '100%',
            padding: '1rem',
            marginBottom: '0',
            textTransform: 'uppercase',
        },
        '& p': {
            font: '2rem',
            fontWeight: '100',
        },
    },
    showOverlay: {
        opacity: '1',
        transform: 'scale(50)',
        position: 'fixed',
        zIndex: '10',
    },
    showCopyMsg: {
        opacity: '1',
        transform: 'scale(1)',
        zIndex: '25',
    },
};
export default styles;
